version: '3'
services:
  app:
    image: pakisan/springwolf-amqp-example:${SPRINGWOLF_VERSION}
    links:
      - amqp
    ports:
      - "8080:8080"
    depends_on:
      - amqp

# guest:guest
  amqp:
    image: rabbitmq:3.8-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'